name: "Deploy to Codigofacilito"
on: 
  push:
    branches: ["main"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
        echo:  "Hacemos pull del codigo"
        echo:  "Correr migraciones"
        echo:  "Generar binario"
        echo:  "Publicar version"
